#!/bin/bash
# Deploys the Accensa contracts to a Stellar network and records the resulting
# contract IDs to deployments/<network>.env, so every deployment leaves a
# committed, independently verifiable trail instead of scrolling past in stdout.
set -euo pipefail

NETWORK="${NETWORK:-testnet}"
IDENTITY="${IDENTITY:-deployer}"
# Testnet native XLM SAC. Override with TOKEN=... to use USDC or another asset.
TOKEN="${TOKEN:-CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC}"
# 17280 ledgers is approximately 1 day at ~5s per ledger.
REFUND_WINDOW_LEDGERS="${REFUND_WINDOW_LEDGERS:-17280}"

OUT_DIR="deployments"
OUT_FILE="$OUT_DIR/$NETWORK.env"

echo "🚀 Building contracts..."
stellar contract build

echo "🔑 Using identity '$IDENTITY' on network '$NETWORK'..."
if ! stellar keys address "$IDENTITY" >/dev/null 2>&1; then
  echo "   Identity not found, generating..."
  stellar keys generate "$IDENTITY" --network "$NETWORK"
fi
DEPLOYER=$(stellar keys address "$IDENTITY")
echo "   Deployer address: $DEPLOYER"

if [ "$NETWORK" = "testnet" ] || [ "$NETWORK" = "futurenet" ]; then
  echo "💎 Ensuring deployer is funded..."
  stellar keys fund "$IDENTITY" --network "$NETWORK" || true
fi

echo "🚢 Deploying ReceiptAnchor..."
ANCHOR_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/receipt_anchor.wasm \
  --source "$IDENTITY" --network "$NETWORK" 2>/dev/null | tail -n 1)
echo "   ReceiptAnchor: $ANCHOR_ID"

echo "🚢 Deploying RefundVault..."
VAULT_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/refund_vault.wasm \
  --source "$IDENTITY" --network "$NETWORK" 2>/dev/null | tail -n 1)
echo "   RefundVault: $VAULT_ID"

echo "⚙️  Initializing ReceiptAnchor..."
stellar contract invoke --id "$ANCHOR_ID" --source "$IDENTITY" --network "$NETWORK" \
  -- initialize --merchant "$DEPLOYER"

echo "⚙️  Initializing RefundVault..."
stellar contract invoke --id "$VAULT_ID" --source "$IDENTITY" --network "$NETWORK" \
  -- initialize --merchant "$DEPLOYER" --token "$TOKEN" \
  --refund_window_ledgers "$REFUND_WINDOW_LEDGERS"

mkdir -p "$OUT_DIR"
cat > "$OUT_FILE" <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK
NEXT_PUBLIC_RECEIPT_ANCHOR_ID=$ANCHOR_ID
NEXT_PUBLIC_REFUND_VAULT_ID=$VAULT_ID
MERCHANT_ADDRESS=$DEPLOYER
TOKEN_ADDRESS=$TOKEN
REFUND_WINDOW_LEDGERS=$REFUND_WINDOW_LEDGERS
EOF

echo ""
echo "==========================================================="
echo "🎉 DEPLOYMENT COMPLETE"
echo "==========================================================="
cat "$OUT_FILE"
echo "==========================================================="
echo "Recorded to $OUT_FILE — commit this file."
echo "Explorer: https://stellar.expert/explorer/$NETWORK/contract/$ANCHOR_ID"
echo "          https://stellar.expert/explorer/$NETWORK/contract/$VAULT_ID"
